/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum EFeatureType {
  F_UNKNOWN = 0,
  F_BOOL = 5,
  F_CHAR = 10,
  F_BYTE = 20,
  F_SHORT = 30,
  F_WORD = 40,
  F_INT = 50,
  F_UINT = 60,
  F_LONG = 70,
  F_ULONG = 80,
  F_SHORTREAL = 90,
  F_DREAL = 100,
  F_LONGREAL = 110,
  F_ANY = 1000
}
