/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum EFeatureClass {
  C_UNKNOWN = 0,
  C_SIMPLE = 10,
  C_SPARSE = 20,
  C_STRING = 30,
  C_COMBINED = 40,
  C_COMBINED_DOT = 60,
  C_WD = 70,
  C_SPEC = 80,
  C_WEIGHTEDSPEC = 90,
  C_POLY = 100,
  C_STREAMING_SIMPLE = 110,
  C_STREAMING_SPARSE = 120,
  C_STREAMING_STRING = 130,
  C_STREAMING_VW = 140,
  C_ANY = 1000
}
