/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum ETransformType {
  T_LINEAR,
  T_LOG,
  T_LOG_PLUS1,
  T_LOG_PLUS3,
  T_LINEAR_PLUS3
}
