/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class EuclidianDistance : RealDistance {
  private HandleRef swigCPtr;

  internal EuclidianDistance(IntPtr cPtr, bool cMemoryOwn) : base(modshogunPINVOKE.EuclidianDistanceUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(EuclidianDistance obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~EuclidianDistance() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          modshogunPINVOKE.delete_EuclidianDistance(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public EuclidianDistance() : this(modshogunPINVOKE.new_EuclidianDistance__SWIG_0(), true) {
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
  }

  public EuclidianDistance(RealFeatures l, RealFeatures r) : this(modshogunPINVOKE.new_EuclidianDistance__SWIG_1(RealFeatures.getCPtr(l), RealFeatures.getCPtr(r)), true) {
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual bool get_disable_sqrt() {
    bool ret = modshogunPINVOKE.EuclidianDistance_get_disable_sqrt(swigCPtr);
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void set_disable_sqrt(bool state) {
    modshogunPINVOKE.EuclidianDistance_set_disable_sqrt(swigCPtr, state);
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
  }

}
