/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class GaussianShiftKernel : GaussianKernel {
  private HandleRef swigCPtr;

  internal GaussianShiftKernel(IntPtr cPtr, bool cMemoryOwn) : base(modshogunPINVOKE.GaussianShiftKernelUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(GaussianShiftKernel obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~GaussianShiftKernel() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          modshogunPINVOKE.delete_GaussianShiftKernel(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public GaussianShiftKernel() : this(modshogunPINVOKE.new_GaussianShiftKernel__SWIG_0(), true) {
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
  }

  public GaussianShiftKernel(int size, double width, int max_shift, int shift_step) : this(modshogunPINVOKE.new_GaussianShiftKernel__SWIG_1(size, width, max_shift, shift_step), true) {
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
  }

  public GaussianShiftKernel(RealFeatures l, RealFeatures r, double width, int max_shift, int shift_step, int size) : this(modshogunPINVOKE.new_GaussianShiftKernel__SWIG_2(RealFeatures.getCPtr(l), RealFeatures.getCPtr(r), width, max_shift, shift_step, size), true) {
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
  }

  public GaussianShiftKernel(RealFeatures l, RealFeatures r, double width, int max_shift, int shift_step) : this(modshogunPINVOKE.new_GaussianShiftKernel__SWIG_3(RealFeatures.getCPtr(l), RealFeatures.getCPtr(r), width, max_shift, shift_step), true) {
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
  }

}
