/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class modshogun {
  public static void init_shogun(SWIGTYPE_p_f_p_FILE_p_q_const__char__void print_message, SWIGTYPE_p_f_p_FILE_p_q_const__char__void print_warning, SWIGTYPE_p_f_p_FILE_p_q_const__char__void print_error, SWIGTYPE_p_f_r_bool_r_bool__void cancel_computations) {
    modshogunPINVOKE.init_shogun__SWIG_0(SWIGTYPE_p_f_p_FILE_p_q_const__char__void.getCPtr(print_message), SWIGTYPE_p_f_p_FILE_p_q_const__char__void.getCPtr(print_warning), SWIGTYPE_p_f_p_FILE_p_q_const__char__void.getCPtr(print_error), SWIGTYPE_p_f_r_bool_r_bool__void.getCPtr(cancel_computations));
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void init_shogun(SWIGTYPE_p_f_p_FILE_p_q_const__char__void print_message, SWIGTYPE_p_f_p_FILE_p_q_const__char__void print_warning, SWIGTYPE_p_f_p_FILE_p_q_const__char__void print_error) {
    modshogunPINVOKE.init_shogun__SWIG_1(SWIGTYPE_p_f_p_FILE_p_q_const__char__void.getCPtr(print_message), SWIGTYPE_p_f_p_FILE_p_q_const__char__void.getCPtr(print_warning), SWIGTYPE_p_f_p_FILE_p_q_const__char__void.getCPtr(print_error));
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void init_shogun(SWIGTYPE_p_f_p_FILE_p_q_const__char__void print_message, SWIGTYPE_p_f_p_FILE_p_q_const__char__void print_warning) {
    modshogunPINVOKE.init_shogun__SWIG_2(SWIGTYPE_p_f_p_FILE_p_q_const__char__void.getCPtr(print_message), SWIGTYPE_p_f_p_FILE_p_q_const__char__void.getCPtr(print_warning));
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void init_shogun(SWIGTYPE_p_f_p_FILE_p_q_const__char__void print_message) {
    modshogunPINVOKE.init_shogun__SWIG_3(SWIGTYPE_p_f_p_FILE_p_q_const__char__void.getCPtr(print_message));
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void init_shogun() {
    modshogunPINVOKE.init_shogun__SWIG_4();
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void init_shogun_with_defaults() {
    modshogunPINVOKE.init_shogun_with_defaults();
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void exit_shogun() {
    modshogunPINVOKE.exit_shogun();
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void set_global_io(SGIO io) {
    modshogunPINVOKE.set_global_io(SGIO.getCPtr(io));
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
  }

  public static SGIO get_global_io() {
    IntPtr cPtr = modshogunPINVOKE.get_global_io();
    SGIO ret = (cPtr == IntPtr.Zero) ? null : new SGIO(cPtr, false);
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static void set_global_parallel(Parallel parallel) {
    modshogunPINVOKE.set_global_parallel(Parallel.getCPtr(parallel));
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
  }

  public static Parallel get_global_parallel() {
    IntPtr cPtr = modshogunPINVOKE.get_global_parallel();
    Parallel ret = (cPtr == IntPtr.Zero) ? null : new Parallel(cPtr, false);
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static void set_global_version(Version version) {
    modshogunPINVOKE.set_global_version(Version.getCPtr(version));
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
  }

  public static Version get_global_version() {
    IntPtr cPtr = modshogunPINVOKE.get_global_version();
    Version ret = (cPtr == IntPtr.Zero) ? null : new Version(cPtr, false);
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static void set_global_math(Math math) {
    modshogunPINVOKE.set_global_math(Math.getCPtr(math));
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
  }

  public static Math get_global_math() {
    IntPtr cPtr = modshogunPINVOKE.get_global_math();
    Math ret = (cPtr == IntPtr.Zero) ? null : new Math(cPtr, false);
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SGIO sg_io {
    set {
      modshogunPINVOKE.sg_io_set(SGIO.getCPtr(value));
      if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      IntPtr cPtr = modshogunPINVOKE.sg_io_get();
      SGIO ret = (cPtr == IntPtr.Zero) ? null : new SGIO(cPtr, false);
      if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public static string c_string_of_substring(SWIGTYPE_p_shogun__substring s) {
    string ret = modshogunPINVOKE.c_string_of_substring(SWIGTYPE_p_shogun__substring.getCPtr(s));
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static void print_substring(SWIGTYPE_p_shogun__substring s) {
    modshogunPINVOKE.print_substring(SWIGTYPE_p_shogun__substring.getCPtr(s));
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
  }

  public static float float_of_substring(SWIGTYPE_p_shogun__substring s) {
    float ret = modshogunPINVOKE.float_of_substring(SWIGTYPE_p_shogun__substring.getCPtr(s));
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double double_of_substring(SWIGTYPE_p_shogun__substring s) {
    double ret = modshogunPINVOKE.double_of_substring(SWIGTYPE_p_shogun__substring.getCPtr(s));
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int int_of_substring(SWIGTYPE_p_shogun__substring s) {
    int ret = modshogunPINVOKE.int_of_substring(SWIGTYPE_p_shogun__substring.getCPtr(s));
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static uint ulong_of_substring(SWIGTYPE_p_shogun__substring s) {
    uint ret = modshogunPINVOKE.ulong_of_substring(SWIGTYPE_p_shogun__substring.getCPtr(s));
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static uint ss_length(SWIGTYPE_p_shogun__substring s) {
    uint ret = modshogunPINVOKE.ss_length(SWIGTYPE_p_shogun__substring.getCPtr(s));
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static readonly int STRING_LEN = modshogunPINVOKE.STRING_LEN_get();
  public static readonly string STRING_LEN_STR = modshogunPINVOKE.STRING_LEN_STR_get();
  public static readonly char CHAR_CONT_BEGIN = modshogunPINVOKE.CHAR_CONT_BEGIN_get();
  public static readonly char CHAR_CONT_END = modshogunPINVOKE.CHAR_CONT_END_get();
  public static readonly char CHAR_ITEM_BEGIN = modshogunPINVOKE.CHAR_ITEM_BEGIN_get();
  public static readonly char CHAR_ITEM_END = modshogunPINVOKE.CHAR_ITEM_END_get();
  public static readonly char CHAR_SGSERIAL_BEGIN = modshogunPINVOKE.CHAR_SGSERIAL_BEGIN_get();
  public static readonly char CHAR_SGSERIAL_END = modshogunPINVOKE.CHAR_SGSERIAL_END_get();
  public static readonly char CHAR_STRING_BEGIN = modshogunPINVOKE.CHAR_STRING_BEGIN_get();
  public static readonly char CHAR_STRING_END = modshogunPINVOKE.CHAR_STRING_END_get();
  public static readonly char CHAR_SPARSE_BEGIN = modshogunPINVOKE.CHAR_SPARSE_BEGIN_get();
  public static readonly char CHAR_SPARSE_END = modshogunPINVOKE.CHAR_SPARSE_END_get();
  public static readonly char CHAR_TYPE_END = modshogunPINVOKE.CHAR_TYPE_END_get();
  public static readonly string STR_SGSERIAL_NULL = modshogunPINVOKE.STR_SGSERIAL_NULL_get();
  public static readonly int RNG_SEED_SIZE = modshogunPINVOKE.RNG_SEED_SIZE_get();
  public static readonly int LOGSUM_TBL = modshogunPINVOKE.LOGSUM_TBL_get();
  public static readonly double DEF_PRECISION = modshogunPINVOKE.DEF_PRECISION_get();
}
