/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class OnlineSVMSGD : OnlineLinearMachine {
  private HandleRef swigCPtr;

  internal OnlineSVMSGD(IntPtr cPtr, bool cMemoryOwn) : base(modshogunPINVOKE.OnlineSVMSGDUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(OnlineSVMSGD obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~OnlineSVMSGD() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          modshogunPINVOKE.delete_OnlineSVMSGD(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public OnlineSVMSGD() : this(modshogunPINVOKE.new_OnlineSVMSGD__SWIG_0(), true) {
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
  }

  public OnlineSVMSGD(double C) : this(modshogunPINVOKE.new_OnlineSVMSGD__SWIG_1(C), true) {
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
  }

  public OnlineSVMSGD(double C, StreamingDotFeatures traindat) : this(modshogunPINVOKE.new_OnlineSVMSGD__SWIG_2(C, StreamingDotFeatures.getCPtr(traindat)), true) {
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
  }

  public override bool train(Features data) {
    bool ret = modshogunPINVOKE.OnlineSVMSGD_train__SWIG_0(swigCPtr, Features.getCPtr(data));
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override bool train() {
    bool ret = modshogunPINVOKE.OnlineSVMSGD_train__SWIG_1(swigCPtr);
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void set_C(double c_neg, double c_pos) {
    modshogunPINVOKE.OnlineSVMSGD_set_C(swigCPtr, c_neg, c_pos);
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
  }

  public double get_C1() {
    double ret = modshogunPINVOKE.OnlineSVMSGD_get_C1(swigCPtr);
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double get_C2() {
    double ret = modshogunPINVOKE.OnlineSVMSGD_get_C2(swigCPtr);
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void set_epochs(int e) {
    modshogunPINVOKE.OnlineSVMSGD_set_epochs(swigCPtr, e);
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
  }

  public int get_epochs() {
    int ret = modshogunPINVOKE.OnlineSVMSGD_get_epochs(swigCPtr);
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void set_lambda(double l) {
    modshogunPINVOKE.OnlineSVMSGD_set_lambda(swigCPtr, l);
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
  }

  public double get_lambda() {
    double ret = modshogunPINVOKE.OnlineSVMSGD_get_lambda(swigCPtr);
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void set_bias_enabled(bool enable_bias) {
    modshogunPINVOKE.OnlineSVMSGD_set_bias_enabled(swigCPtr, enable_bias);
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool get_bias_enabled() {
    bool ret = modshogunPINVOKE.OnlineSVMSGD_get_bias_enabled(swigCPtr);
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void set_regularized_bias_enabled(bool enable_bias) {
    modshogunPINVOKE.OnlineSVMSGD_set_regularized_bias_enabled(swigCPtr, enable_bias);
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool get_regularized_bias_enabled() {
    bool ret = modshogunPINVOKE.OnlineSVMSGD_get_regularized_bias_enabled(swigCPtr);
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void set_loss_function(SWIGTYPE_p_CLossFunction loss_func) {
    modshogunPINVOKE.OnlineSVMSGD_set_loss_function(swigCPtr, SWIGTYPE_p_CLossFunction.getCPtr(loss_func));
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_CLossFunction get_loss_function() {
    IntPtr cPtr = modshogunPINVOKE.OnlineSVMSGD_get_loss_function(swigCPtr);
    SWIGTYPE_p_CLossFunction ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_CLossFunction(cPtr, false);
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}
