/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class SparseSpatialSampleStringKernel : StringCharKernel {
  private HandleRef swigCPtr;

  internal SparseSpatialSampleStringKernel(IntPtr cPtr, bool cMemoryOwn) : base(modshogunPINVOKE.SparseSpatialSampleStringKernelUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(SparseSpatialSampleStringKernel obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~SparseSpatialSampleStringKernel() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          modshogunPINVOKE.delete_SparseSpatialSampleStringKernel(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public SparseSpatialSampleStringKernel() : this(modshogunPINVOKE.new_SparseSpatialSampleStringKernel__SWIG_0(), true) {
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
  }

  public SparseSpatialSampleStringKernel(StringCharFeatures l, StringCharFeatures r) : this(modshogunPINVOKE.new_SparseSpatialSampleStringKernel__SWIG_1(StringCharFeatures.getCPtr(l), StringCharFeatures.getCPtr(r)), true) {
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
  }

  public void set_d(int max_distance) {
    modshogunPINVOKE.SparseSpatialSampleStringKernel_set_d(swigCPtr, max_distance);
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
  }

  public int get_d() {
    int ret = modshogunPINVOKE.SparseSpatialSampleStringKernel_get_d(swigCPtr);
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void set_t(int sequence_length) {
    modshogunPINVOKE.SparseSpatialSampleStringKernel_set_t(swigCPtr, sequence_length);
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
  }

  public int get_t() {
    int ret = modshogunPINVOKE.SparseSpatialSampleStringKernel_get_t(swigCPtr);
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}
