/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class StreamingVwFeatures : StreamingDotFeatures {
  private HandleRef swigCPtr;

  internal StreamingVwFeatures(IntPtr cPtr, bool cMemoryOwn) : base(modshogunPINVOKE.StreamingVwFeaturesUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(StreamingVwFeatures obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~StreamingVwFeatures() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          modshogunPINVOKE.delete_StreamingVwFeatures(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public StreamingVwFeatures() : this(modshogunPINVOKE.new_StreamingVwFeatures__SWIG_0(), true) {
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
  }

  public StreamingVwFeatures(StreamingVwFile file, bool is_labelled, int size) : this(modshogunPINVOKE.new_StreamingVwFeatures__SWIG_1(StreamingVwFile.getCPtr(file), is_labelled, size), true) {
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
  }

  public StreamingVwFeatures(StreamingVwCacheFile file, bool is_labelled, int size) : this(modshogunPINVOKE.new_StreamingVwFeatures__SWIG_2(StreamingVwCacheFile.getCPtr(file), is_labelled, size), true) {
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual SWIGTYPE_p_CVwEnvironment get_env() {
    IntPtr cPtr = modshogunPINVOKE.StreamingVwFeatures_get_env(swigCPtr);
    SWIGTYPE_p_CVwEnvironment ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_CVwEnvironment(cPtr, false);
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void set_env(SWIGTYPE_p_CVwEnvironment vw_env) {
    modshogunPINVOKE.StreamingVwFeatures_set_env(swigCPtr, SWIGTYPE_p_CVwEnvironment.getCPtr(vw_env));
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual SWIGTYPE_p_VwExample get_example() {
    IntPtr cPtr = modshogunPINVOKE.StreamingVwFeatures_get_example(swigCPtr);
    SWIGTYPE_p_VwExample ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_VwExample(cPtr, false);
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override void expand_if_required(SWIGTYPE_p_float vec, SWIGTYPE_p_int len) {
    modshogunPINVOKE.StreamingVwFeatures_expand_if_required__SWIG_0(swigCPtr, SWIGTYPE_p_float.getCPtr(vec), SWIGTYPE_p_int.getCPtr(len));
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
  }

  public override void expand_if_required(SWIGTYPE_p_double vec, SWIGTYPE_p_int len) {
    modshogunPINVOKE.StreamingVwFeatures_expand_if_required__SWIG_1(swigCPtr, SWIGTYPE_p_double.getCPtr(vec), SWIGTYPE_p_int.getCPtr(len));
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual float real_weight(float w, float gravity) {
    float ret = modshogunPINVOKE.StreamingVwFeatures_real_weight(swigCPtr, w, gravity);
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual float dense_dot_truncated(SWIGTYPE_p_float vec2, SWIGTYPE_p_VwExample ex, float gravity) {
    float ret = modshogunPINVOKE.StreamingVwFeatures_dense_dot_truncated(swigCPtr, SWIGTYPE_p_float.getCPtr(vec2), SWIGTYPE_p_VwExample.getCPtr(ex), gravity);
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}
