/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class StreamingFileFromFeatures : StreamingFile {
  private HandleRef swigCPtr;

  internal StreamingFileFromFeatures(IntPtr cPtr, bool cMemoryOwn) : base(modshogunPINVOKE.StreamingFileFromFeaturesUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(StreamingFileFromFeatures obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~StreamingFileFromFeatures() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          modshogunPINVOKE.delete_StreamingFileFromFeatures(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public StreamingFileFromFeatures() : this(modshogunPINVOKE.new_StreamingFileFromFeatures__SWIG_0(), true) {
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
  }

  public StreamingFileFromFeatures(SWIGTYPE_p_CFeatures feat) : this(modshogunPINVOKE.new_StreamingFileFromFeatures__SWIG_1(SWIGTYPE_p_CFeatures.getCPtr(feat)), true) {
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
  }

  public StreamingFileFromFeatures(SWIGTYPE_p_CFeatures feat, SWIGTYPE_p_double lab) : this(modshogunPINVOKE.new_StreamingFileFromFeatures__SWIG_2(SWIGTYPE_p_CFeatures.getCPtr(feat), SWIGTYPE_p_double.getCPtr(lab)), true) {
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void set_features(SWIGTYPE_p_CFeatures feat) {
    modshogunPINVOKE.StreamingFileFromFeatures_set_features(swigCPtr, SWIGTYPE_p_CFeatures.getCPtr(feat));
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void set_labels(SWIGTYPE_p_double lab) {
    modshogunPINVOKE.StreamingFileFromFeatures_set_labels(swigCPtr, SWIGTYPE_p_double.getCPtr(lab));
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
  }

}
