/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class SWIGTYPE_m_CVwParser__f_p_CIOBuffer_r_p_VwExample__int {
  private string swigCMemberPtr;

  internal SWIGTYPE_m_CVwParser__f_p_CIOBuffer_r_p_VwExample__int(string cMemberPtr, bool futureUse) {
    swigCMemberPtr = cMemberPtr;
  }

  protected SWIGTYPE_m_CVwParser__f_p_CIOBuffer_r_p_VwExample__int() {
    swigCMemberPtr = null;
  }

  internal static string getCMemberPtr(SWIGTYPE_m_CVwParser__f_p_CIOBuffer_r_p_VwExample__int obj) {
    return obj.swigCMemberPtr;
  }
}
