/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class WeightedDegreePositionStringKernel : StringCharKernel {
  private HandleRef swigCPtr;

  internal WeightedDegreePositionStringKernel(IntPtr cPtr, bool cMemoryOwn) : base(modshogunPINVOKE.WeightedDegreePositionStringKernelUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(WeightedDegreePositionStringKernel obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~WeightedDegreePositionStringKernel() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          modshogunPINVOKE.delete_WeightedDegreePositionStringKernel(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public WeightedDegreePositionStringKernel() : this(modshogunPINVOKE.new_WeightedDegreePositionStringKernel__SWIG_0(), true) {
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
  }

  public WeightedDegreePositionStringKernel(int size, int degree, int max_mismatch, int mkl_stepsize) : this(modshogunPINVOKE.new_WeightedDegreePositionStringKernel__SWIG_1(size, degree, max_mismatch, mkl_stepsize), true) {
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
  }

  public WeightedDegreePositionStringKernel(int size, int degree, int max_mismatch) : this(modshogunPINVOKE.new_WeightedDegreePositionStringKernel__SWIG_2(size, degree, max_mismatch), true) {
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
  }

  public WeightedDegreePositionStringKernel(int size, int degree) : this(modshogunPINVOKE.new_WeightedDegreePositionStringKernel__SWIG_3(size, degree), true) {
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
  }

  public WeightedDegreePositionStringKernel(int size, SWIGTYPE_p_double weights, int degree, int max_mismatch, SWIGTYPE_p_int shift, int shift_len, int mkl_stepsize) : this(modshogunPINVOKE.new_WeightedDegreePositionStringKernel__SWIG_4(size, SWIGTYPE_p_double.getCPtr(weights), degree, max_mismatch, SWIGTYPE_p_int.getCPtr(shift), shift_len, mkl_stepsize), true) {
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
  }

  public WeightedDegreePositionStringKernel(int size, SWIGTYPE_p_double weights, int degree, int max_mismatch, SWIGTYPE_p_int shift, int shift_len) : this(modshogunPINVOKE.new_WeightedDegreePositionStringKernel__SWIG_5(size, SWIGTYPE_p_double.getCPtr(weights), degree, max_mismatch, SWIGTYPE_p_int.getCPtr(shift), shift_len), true) {
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
  }

  public WeightedDegreePositionStringKernel(StringCharFeatures l, StringCharFeatures r, int degree) : this(modshogunPINVOKE.new_WeightedDegreePositionStringKernel__SWIG_6(StringCharFeatures.getCPtr(l), StringCharFeatures.getCPtr(r), degree), true) {
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
  }

  public override bool init_optimization(int p_count, SWIGTYPE_p_int IDX, SWIGTYPE_p_double alphas) {
    bool ret = modshogunPINVOKE.WeightedDegreePositionStringKernel_init_optimization__SWIG_0(swigCPtr, p_count, SWIGTYPE_p_int.getCPtr(IDX), SWIGTYPE_p_double.getCPtr(alphas));
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual bool init_optimization(int count, SWIGTYPE_p_int IDX, SWIGTYPE_p_double alphas, int tree_num, int upto_tree) {
    bool ret = modshogunPINVOKE.WeightedDegreePositionStringKernel_init_optimization__SWIG_1(swigCPtr, count, SWIGTYPE_p_int.getCPtr(IDX), SWIGTYPE_p_double.getCPtr(alphas), tree_num, upto_tree);
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual bool init_optimization(int count, SWIGTYPE_p_int IDX, SWIGTYPE_p_double alphas, int tree_num) {
    bool ret = modshogunPINVOKE.WeightedDegreePositionStringKernel_init_optimization__SWIG_2(swigCPtr, count, SWIGTYPE_p_int.getCPtr(IDX), SWIGTYPE_p_double.getCPtr(alphas), tree_num);
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SWIGTYPE_p_void compute_batch_helper(SWIGTYPE_p_void p) {
    IntPtr cPtr = modshogunPINVOKE.WeightedDegreePositionStringKernel_compute_batch_helper(SWIGTYPE_p_void.getCPtr(p));
    SWIGTYPE_p_void ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override void compute_batch(int num_vec, SWIGTYPE_p_int vec_idx, SWIGTYPE_p_double target, int num_suppvec, SWIGTYPE_p_int IDX, SWIGTYPE_p_double alphas, double factor) {
    modshogunPINVOKE.WeightedDegreePositionStringKernel_compute_batch__SWIG_0(swigCPtr, num_vec, SWIGTYPE_p_int.getCPtr(vec_idx), SWIGTYPE_p_double.getCPtr(target), num_suppvec, SWIGTYPE_p_int.getCPtr(IDX), SWIGTYPE_p_double.getCPtr(alphas), factor);
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
  }

  public override void compute_batch(int num_vec, SWIGTYPE_p_int vec_idx, SWIGTYPE_p_double target, int num_suppvec, SWIGTYPE_p_int IDX, SWIGTYPE_p_double alphas) {
    modshogunPINVOKE.WeightedDegreePositionStringKernel_compute_batch__SWIG_1(swigCPtr, num_vec, SWIGTYPE_p_int.getCPtr(vec_idx), SWIGTYPE_p_double.getCPtr(target), num_suppvec, SWIGTYPE_p_int.getCPtr(IDX), SWIGTYPE_p_double.getCPtr(alphas));
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_double compute_abs_weights(SWIGTYPE_p_int len) {
    IntPtr cPtr = modshogunPINVOKE.WeightedDegreePositionStringKernel_compute_abs_weights(swigCPtr, SWIGTYPE_p_int.getCPtr(len));
    SWIGTYPE_p_double ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_double(cPtr, false);
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool is_tree_initialized() {
    bool ret = modshogunPINVOKE.WeightedDegreePositionStringKernel_is_tree_initialized(swigCPtr);
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int get_max_mismatch() {
    int ret = modshogunPINVOKE.WeightedDegreePositionStringKernel_get_max_mismatch(swigCPtr);
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int get_degree() {
    int ret = modshogunPINVOKE.WeightedDegreePositionStringKernel_get_degree(swigCPtr);
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_double get_degree_weights(SWIGTYPE_p_int d, SWIGTYPE_p_int len) {
    IntPtr cPtr = modshogunPINVOKE.WeightedDegreePositionStringKernel_get_degree_weights(swigCPtr, SWIGTYPE_p_int.getCPtr(d), SWIGTYPE_p_int.getCPtr(len));
    SWIGTYPE_p_double ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_double(cPtr, false);
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_double get_weights(SWIGTYPE_p_int num_weights) {
    IntPtr cPtr = modshogunPINVOKE.WeightedDegreePositionStringKernel_get_weights(swigCPtr, SWIGTYPE_p_int.getCPtr(num_weights));
    SWIGTYPE_p_double ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_double(cPtr, false);
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_double get_position_weights(SWIGTYPE_p_int len) {
    IntPtr cPtr = modshogunPINVOKE.WeightedDegreePositionStringKernel_get_position_weights(swigCPtr, SWIGTYPE_p_int.getCPtr(len));
    SWIGTYPE_p_double ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_double(cPtr, false);
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void set_shifts(int[] shifts) {
    modshogunPINVOKE.WeightedDegreePositionStringKernel_set_shifts(swigCPtr, shifts.Length, shifts);
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool set_weights(double[,] new_weights) {
    bool ret = modshogunPINVOKE.WeightedDegreePositionStringKernel_set_weights(swigCPtr, new_weights.GetLength(0), new_weights.GetLength(1), new_weights);
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual bool set_wd_weights() {
    bool ret = modshogunPINVOKE.WeightedDegreePositionStringKernel_set_wd_weights(swigCPtr);
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void set_position_weights(double[] pws) {
    modshogunPINVOKE.WeightedDegreePositionStringKernel_set_position_weights(swigCPtr, pws.Length, pws);
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool set_position_weights_lhs(SWIGTYPE_p_double pws, int len, int num) {
    bool ret = modshogunPINVOKE.WeightedDegreePositionStringKernel_set_position_weights_lhs(swigCPtr, SWIGTYPE_p_double.getCPtr(pws), len, num);
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool set_position_weights_rhs(SWIGTYPE_p_double pws, int len, int num) {
    bool ret = modshogunPINVOKE.WeightedDegreePositionStringKernel_set_position_weights_rhs(swigCPtr, SWIGTYPE_p_double.getCPtr(pws), len, num);
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool init_block_weights() {
    bool ret = modshogunPINVOKE.WeightedDegreePositionStringKernel_init_block_weights(swigCPtr);
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool init_block_weights_from_wd() {
    bool ret = modshogunPINVOKE.WeightedDegreePositionStringKernel_init_block_weights_from_wd(swigCPtr);
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool init_block_weights_from_wd_external() {
    bool ret = modshogunPINVOKE.WeightedDegreePositionStringKernel_init_block_weights_from_wd_external(swigCPtr);
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool init_block_weights_const() {
    bool ret = modshogunPINVOKE.WeightedDegreePositionStringKernel_init_block_weights_const(swigCPtr);
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool init_block_weights_linear() {
    bool ret = modshogunPINVOKE.WeightedDegreePositionStringKernel_init_block_weights_linear(swigCPtr);
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool init_block_weights_sqpoly() {
    bool ret = modshogunPINVOKE.WeightedDegreePositionStringKernel_init_block_weights_sqpoly(swigCPtr);
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool init_block_weights_cubicpoly() {
    bool ret = modshogunPINVOKE.WeightedDegreePositionStringKernel_init_block_weights_cubicpoly(swigCPtr);
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool init_block_weights_exp() {
    bool ret = modshogunPINVOKE.WeightedDegreePositionStringKernel_init_block_weights_exp(swigCPtr);
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool init_block_weights_log() {
    bool ret = modshogunPINVOKE.WeightedDegreePositionStringKernel_init_block_weights_log(swigCPtr);
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool delete_position_weights() {
    bool ret = modshogunPINVOKE.WeightedDegreePositionStringKernel_delete_position_weights(swigCPtr);
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool delete_position_weights_lhs() {
    bool ret = modshogunPINVOKE.WeightedDegreePositionStringKernel_delete_position_weights_lhs(swigCPtr);
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool delete_position_weights_rhs() {
    bool ret = modshogunPINVOKE.WeightedDegreePositionStringKernel_delete_position_weights_rhs(swigCPtr);
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual double compute_by_tree(int idx) {
    double ret = modshogunPINVOKE.WeightedDegreePositionStringKernel_compute_by_tree__SWIG_0(swigCPtr, idx);
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void compute_by_tree(int idx, SWIGTYPE_p_double LevelContrib) {
    modshogunPINVOKE.WeightedDegreePositionStringKernel_compute_by_tree__SWIG_1(swigCPtr, idx, SWIGTYPE_p_double.getCPtr(LevelContrib));
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_double compute_scoring(int max_degree, SWIGTYPE_p_int num_feat, SWIGTYPE_p_int num_sym, SWIGTYPE_p_double target, int num_suppvec, SWIGTYPE_p_int IDX, SWIGTYPE_p_double weights) {
    IntPtr cPtr = modshogunPINVOKE.WeightedDegreePositionStringKernel_compute_scoring(swigCPtr, max_degree, SWIGTYPE_p_int.getCPtr(num_feat), SWIGTYPE_p_int.getCPtr(num_sym), SWIGTYPE_p_double.getCPtr(target), num_suppvec, SWIGTYPE_p_int.getCPtr(IDX), SWIGTYPE_p_double.getCPtr(weights));
    SWIGTYPE_p_double ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_double(cPtr, false);
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string compute_consensus(SWIGTYPE_p_int num_feat, int num_suppvec, SWIGTYPE_p_int IDX, SWIGTYPE_p_double alphas) {
    string ret = modshogunPINVOKE.WeightedDegreePositionStringKernel_compute_consensus(swigCPtr, SWIGTYPE_p_int.getCPtr(num_feat), num_suppvec, SWIGTYPE_p_int.getCPtr(IDX), SWIGTYPE_p_double.getCPtr(alphas));
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_double extract_w(int max_degree, SWIGTYPE_p_int num_feat, SWIGTYPE_p_int num_sym, SWIGTYPE_p_double w_result, int num_suppvec, SWIGTYPE_p_int IDX, SWIGTYPE_p_double alphas) {
    IntPtr cPtr = modshogunPINVOKE.WeightedDegreePositionStringKernel_extract_w(swigCPtr, max_degree, SWIGTYPE_p_int.getCPtr(num_feat), SWIGTYPE_p_int.getCPtr(num_sym), SWIGTYPE_p_double.getCPtr(w_result), num_suppvec, SWIGTYPE_p_int.getCPtr(IDX), SWIGTYPE_p_double.getCPtr(alphas));
    SWIGTYPE_p_double ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_double(cPtr, false);
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_double compute_POIM(int max_degree, SWIGTYPE_p_int num_feat, SWIGTYPE_p_int num_sym, SWIGTYPE_p_double poim_result, int num_suppvec, SWIGTYPE_p_int IDX, SWIGTYPE_p_double alphas, SWIGTYPE_p_double distrib) {
    IntPtr cPtr = modshogunPINVOKE.WeightedDegreePositionStringKernel_compute_POIM(swigCPtr, max_degree, SWIGTYPE_p_int.getCPtr(num_feat), SWIGTYPE_p_int.getCPtr(num_sym), SWIGTYPE_p_double.getCPtr(poim_result), num_suppvec, SWIGTYPE_p_int.getCPtr(IDX), SWIGTYPE_p_double.getCPtr(alphas), SWIGTYPE_p_double.getCPtr(distrib));
    SWIGTYPE_p_double ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_double(cPtr, false);
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void prepare_POIM2(SWIGTYPE_p_double distrib, int num_sym, int num_feat) {
    modshogunPINVOKE.WeightedDegreePositionStringKernel_prepare_POIM2(swigCPtr, SWIGTYPE_p_double.getCPtr(distrib), num_sym, num_feat);
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
  }

  public void compute_POIM2(int max_degree, SVM svm) {
    modshogunPINVOKE.WeightedDegreePositionStringKernel_compute_POIM2(swigCPtr, max_degree, SVM.getCPtr(svm));
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
  }

  public void get_POIM2(SWIGTYPE_p_p_double poim, SWIGTYPE_p_int result_len) {
    modshogunPINVOKE.WeightedDegreePositionStringKernel_get_POIM2(swigCPtr, SWIGTYPE_p_p_double.getCPtr(poim), SWIGTYPE_p_int.getCPtr(result_len));
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
  }

  public void cleanup_POIM2() {
    modshogunPINVOKE.WeightedDegreePositionStringKernel_cleanup_POIM2(swigCPtr);
    if (modshogunPINVOKE.SWIGPendingException.Pending) throw modshogunPINVOKE.SWIGPendingException.Retrieve();
  }

}
